---
config:
  theme: 'redux-dark-color'
---

%% transparent

erDiagram
    Host ||..o{ Test: compile
    Host ||..o{ Docker: run
    Docker ||..o{ Kernel: compile
    Docker ||..o{ Documentation: compile