---
config:
    theme: 'neo-dark'
---

treeView-beta
    include             ## Public headers (1)
    src                 ## Private headers and sources (2)
    tests               ## Test suite for the subproject (3)
        CMakeLists.txt  ## Test suite CMakeLists
    CMakeLists.txt      ## Subproject CMakeLists