---
config:
    theme: 'redux'
---

architecture-beta
group hardware(mdi:chip)[Hardware]
    service keyboard(solar:keyboard-bold)[Keyboard] in hardware
    service monitor(solar:monitor-bold)[Monitor] in hardware

group kernel(mdi:gear)[Kernel]
    service ps2(solar:cpu-bold)[PS2 driver] in kernel
    service vga(solar:cpu-bold)[VGA driver] in kernel

group userspace(mdi:user)[Userspace]
    service user(mdi:user)[User] in userspace

align row monitor keyboard
align row vga ps2 user
align column vga monitor
align column ps2 keyboard

vga{group}:B <--> T:monitor{group}
ps2{group}:B <--> T:keyboard{group}
user{group}:L <--> R:ps2{group}